version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
            apt-get install -y nodejs
            node -v
            npm -v
      - run:
          name: Restore dependencies
          command: dotnet restore
      - run:
          name: Build the solution
          command: dotnet build --no-restore
      - run:
          name: Run tests
          command: dotnet test --no-build --verbosity normal
      - persist_to_workspace:
          root: .
          paths:
            - .

  sonarcloud_scan:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - attach_workspace:
          at: .
      - sonarcloud/scan

workflows:
  build-and-analyze:
    jobs:
      - build
      - sonarcloud_scan:
          requires:
            - build
