version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0
    steps:
      - checkout
      - run:
          name: Restore dependencies
          command: dotnet restore
      - run:
          name: Build project
          command: dotnet build --no-restore
      - run:
          name: Run tests
          command: dotnet test --no-build --logger:trx

  sonarcloud_scan:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:7.0
    steps:
      - checkout
      - sonarcloud/scan

workflows:
  build-and-analyze:
    jobs:
      - build
      - sonarcloud_scan:
          requires:
            - build
