version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.2

jobs:
  build:
    docker:
      - image: cimg/dotnet:8.0  # or cimg/dotnet:6.0 depending on your .NET version
    steps:
      - checkout
      - run:
          name: Restore dependencies
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build --no-restore
      - run:
          name: Run tests
          command: dotnet test --no-build --verbosity normal
      - sonarcloud/scan

workflows:
  build-and-analyze:
    jobs:
      - build
