version: 2.1  # update to version: 2.1 # minor comment tweak

orbs:
  sonarsource: sonarsource/sonarcloud@1.1.1

jobs:
  build:
    docker:
      - image: cimg/dotnet:8.0
    steps:
      - checkout
      - run:
          name: Restore dependencies
          command: dotnet restore
      - run:
          name: Build
          command: dotnet build --no-restore
      - run:
          name: Test
          command: dotnet test --no-build --verbosity normal
      - sonarsource/scan

workflows:
  version: 2
  build-and-analyze:
    jobs:
      - build
