version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:
  build:
    docker:
      - image: cimg/dotnet:7.0
    steps:
      - checkout

      - run:
          name: Restore Dependencies
          command: dotnet restore

      - run:
          name: Build Solution
          command: dotnet build --no-restore

      - run:
          name: Run Tests
          command: dotnet test --no-build --collect:"XPlat Code Coverage"

      - run:
          name: Generate Coverage Report
          command: |
            dotnet tool install --global dotnet-reportgenerator-globaltool
            reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coverage-report -reporttypes:Html

      - sonarcloud/scan

workflows:
  main:
    jobs:
      - build
