version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - checkout

      - run:
          name: Restore dependencies
          command: dotnet restore

      - run:
          name: Build the solution
          command: dotnet build --no-restore

      - run:
          name: Run tests
          command: dotnet test --no-build --verbosity normal

      - persist_to_workspace:
          root: .
          paths:
            - .

  sonarcloud_scan:
    docker:
      - image: cimg/openjdk:21.0  # Java 21 supports class file version 61
    steps:
      - checkout
      - attach_workspace:
          at: .

      - run:
          name: Install unzip and Node.js
          command: |
            sudo apt-get update
            sudo apt-get install -y unzip curl gnupg
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs

      - sonarcloud/scan

workflows:
  build-and-analyze:
    jobs:
      - build
      - sonarcloud_scan:
          requires:
            - build
