version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:8.0
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            apt-get update
            apt-get install -y curl gnupg
            curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
            apt-get install -y nodejs
      - run:
          name: Restore dependencies
          command: dotnet restore
      - run:
          name: Build the solution
          command: dotnet build --no-restore
      - run:
          name: Run tests
          command: dotnet test --no-build --verbosity normal
      - persist_to_workspace:
          root: .
          paths:
            - .

  sonarcloud_scan:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Java, unzip, and Node.js
          command: |
            apt-get update
            apt-get install -y openjdk-17-jdk unzip curl gnupg
            curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
            apt-get install -y nodejs
      - run:
          name: Set JAVA_HOME
          command: echo 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64' >> $BASH_ENV
      - sonarcloud/scan

workflows:
  build-and-analyze:
    jobs:
      - build
      - sonarcloud_scan:
          requires:
            - build
